STATUSMAP = {
    'normal':'N',
    'peak':'P',
    'booked':'B',
    'notAvailable':'NA'
}

WISHLIST = (14, 15, 30, 34) # indices of CC details

COMMUNITYCLUBS = [
    ('2400ipogpa-bm', 'OUR TAMPINES HUB CC'),
    ('4010ccmcpa-bm', 'WOODLANDS GALAXY CC'),
    ('4020ccmcpa-bm', 'ACE THE PLACE CC'),
    ('4030ccmcpa-bm', 'QUEENSTOWN CC'),
    ('4040ccmcpa-bm', 'PUNGGOL 21 CC'),
    ('4060ccmcpa-bm', 'ANCHORVALE CC'),
    ('4090ccmcpa-bm', 'AYER RAJAH CC'),
    ('4110ccmcpa-bm', 'BEDOK CC'),
    ('4170ccmcpa-bm', 'BOON LAY CC'),
    ('4190ccmcpa-bm', 'BRADDELL HEIGHTS CC'),
    ('4210ccmcpa-bm', 'BUKIT BATOK CC'),
    ('4270ccmcpa-bm', 'BUKIT MERAH CC'),
    ('4290ccmcpa-bm', 'BUKIT PANJANG CC'),
    ('4310ccmcpa-bm', 'BUKIT TIMAH CC'),
    ('4330ccmcpa-bm', 'BUONA VISTA CC'),
    ('4350ccmcpa-bm', 'CAIRNHILL CC'),
    ('4360ccmcpa-bm', 'CANBERRA CC'),
    ('4370ccmcpa-bm', 'CHANGI SIMEI CC'),
    ('4390ccmcpa-bm', 'TAMPINES CHANGKAT CC'),
    ('4420ccmcpa-bm', 'CHONG PANG CC'),
    ('4430ccmcpa-bm', 'CHUA CHU KANG CC'),
    ('4450ccmcpa-bm', 'CLEMENTI CC'),
    ('4490ccmcpa-bm', 'EUNOS CC'),
    ('4550ccmcpa-bm', 'GEK POH VILLE CC'),
    ('4610ccmcpa-bm', 'HENDERSON CC'),
    ('4630ccmcpa-bm', 'JURONG GREEN CC'),
    ('4640ccmcpa-bm', 'HONG KAH NORTH CC'),
    ('4650ccmcpa-bm', 'JURONG SPRING CC'),
    ('4670ccmcpa-bm', 'HOUGANG CC'),
    ('4690ccmcpa-bm', 'HWI YOH CC'),
    ('4700ccmcpa-bm', 'JALAN BESAR CC'),
    ('4730ccmcpa-bm', 'JOO CHIAT CC'),
    ('4770ccmcpa-bm', 'TAMAN JURONG CC'),
    ('4810ccmcpa-bm', 'KALLANG CC'),
    ('4840ccmcpa-bm', 'KAMPONG GLAM CC'),
    ('4850ccmcpa-bm', 'KAMPONG KEMBANGAN CC'),
    ('4870ccmcpa-bm', 'KAMPONG UBI CC'),
    ('4900ccmcpa-bm', 'KEBUN BARU CC'),
    ('4910ccmcpa-bm', 'KIM SENG CC'),
    ('4970ccmcpa-bm', 'KEAT HONG CC'),
    ('4990ccmcpa-bm', 'LENG KEE CC'),
    ('5010ccmcpa-bm', 'MACPHERSON CC'),
    ('5020ccmcpa-bm', 'MARINE PARADE CC'),
    ('5030ccmcpa-bm', 'MARSILING CC'),
    ('5070ccmcpa-bm', 'MOUNTBATTEN CC'),
    ('5090ccmcpa-bm', 'NANYANG CC'),
    ('5130ccmcpa-bm', 'NEE SOON EAST CC'),
    ('5150ccmcpa-bm', 'NEE SOON SOUTH CC'),
    ('5190ccmcpa-bm', 'PASIR RIS EAST CC'),
    ('5210ccmcpa-bm', 'PASIR RIS ELIAS CC'),
    ('5250ccmcpa-bm', 'TAMPINES NORTH CC'),
    ('5270ccmcpa-bm', 'PAYA LEBAR KOVAN CC'),
    ('5290ccmcpa-bm', 'PEK KIO CC'),
    ('5310ccmcpa-bm', 'POTONG PASIR CC'),
    ('5430ccmcpa-bm', 'RADIN MAS CC'),
    ('5460sscpa-bm', 'SENJA-CASHEW CC FACILITIES'),
    ('5470ccmcpa-bm', 'SEMBAWANG CC'),
    ('5530ccmcpa-bm', 'SIGLAP CC'),
    ('5630ccmcpa-bm', 'TAMPINES WEST CC'),
    ('5650ccmcpa-bm', 'TANGLIN CC'),
    ('5670ccmcpa-bm', 'TANJONG PAGAR CC'),
    ('5690ccmcpa-bm', 'TECK GHEE CC'),
    ('5730ccmcpa-bm', 'TELOK BLANGAH CC'),
    ('5750ccmcpa-bm', 'THOMSON CC'),
    ('5770ccmcpa-bm', 'TIONG BAHRU CC'),
    ('5790ccmcpa-bm', 'TOA PAYOH CENTRAL CC'),
    ('5810ccmcpa-bm', 'TOA PAYOH EAST CC'),
    ('5830ccmcpa-bm', 'TOA PAYOH SOUTH CC'),
    ('5890ccmcpa-bm', 'WEST COAST CC'),
    ('5900ccmcpa-bm', 'THE FRONTIER CC'),
    ('5910ccmcpa-bm', 'WHAMPOA CC'),
    ('5930ccmcpa-bm', 'WOODLANDS CC'),
    ('5950ccmcpa-bm', 'YEW TEE CC'),
    ('5970ccmcpa-bm', 'YIO CHU KANG CC'),
    ('5980ccmcpa-bm', 'YUHUA CC'),
    ('5990ccmcpa-bm', 'ZHENGHUA CC')
]
